export const getRequestAuthSchema = {
	summary: 'Request an authentication token for the provided email',
	description: 'Request an authentication token for the provided email. The email must end with @<AUTH_EMAIL_DOMAIN>',
	produces: ['text/plain'],
	query: {
		required: ['email'],
		type: 'object',
		properties: {
			email: {
				type: 'string',
				description: 'Your email, ending in @<AUTH_EMAIL_DOMAIN>'
			}
		}
	},
	response: {
		204: {
			type: 'null',
			description: 'The authentication token has been succesfully generated and an email was sent.'
		},
		400: {
			type: 'string',
			description: 'Error message'
		}
	}
};

export const getActivateSchema = {
	summary: 'Activates a token for the email if it matches with the one generated on `/request`.',
	description: 'Activates a token for the email if it matches with the one generated on `/request`. Endpoint is used to prove that the user does in fact have access to the provided email.\n\nThe most likely usage is by simpling clicking the link that was automatically generated in the email sent to you.',
	query: {
		type: 'object',
		required: ['email', 'token'],
		properties: {
			email: {
				type: 'string',
				description: 'Email used in the /request endpoint.',
			},
			token: {
				type: 'string',
				description: 'Token sent to your email after having requested it using the /request endpoint.'
			}
		}
	},
	produces: ['text/plain'],
	response: {
		200: {
			content: {
				'text/plain': {
					schema: {
						type: 'string',
						example: 'success'
					}
				}
			}
		}
	}
};

export const getAuthenticateSchema = {
	summary: 'Check if token is valid for an email',
	description: 'Check if the token and email pair have been authenticated.',
	query: {
		required: ['email', 'token'],
		type: 'object',
		properties: {
			email: {
				type: 'string',
				description: 'An email ending in <AUTH_EMAIL_DOMAIN>',
			},
			token: {
				type: 'string',
				description: 'A token generated by the /request endpoint'
			}
		}
	},
	response: {
		200: {
			type: 'boolean'
		}
	}
};
